# Generated by Django 3.2.4 on 2021-06-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0005_schedulinginterval'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checks',
            new_name='Check',
        ),
    ]
