# Generated by Django 3.2.4 on 2021-06-20 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0008_auto_20210619_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('linked_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='description.check')),
                ('notification_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_h', to='description.timeperiod')),
                ('scheduling_interval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='description.schedulinginterval')),
                ('scheduling_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scheduling_h', to='description.timeperiod')),
            ],
        ),
        migrations.AddField(
            model_name='metric',
            name='linked_host',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='description.host'),
            preserve_default=False,
        ),
    ]
