# Generated by Django 3.2.4 on 2021-06-29 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0011_auto_20210629_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('linked_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='description.check')),
                ('linked_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='description.host')),
                ('metric_template', models.ManyToManyField(related_name='_description_metrictemplate_metric_template_+', to='description.MetricTemplate')),
                ('notification_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_mt', to='description.timeperiod')),
                ('scheduling_interval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='description.schedulinginterval')),
                ('scheduling_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scheduling_mt', to='description.timeperiod')),
            ],
        ),
        migrations.CreateModel(
            name='HostTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('host_templates', models.ManyToManyField(related_name='_description_hosttemplate_host_templates_+', to='description.HostTemplate')),
                ('linked_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='description.check')),
                ('notification_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_ht', to='description.timeperiod')),
                ('scheduling_interval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='description.schedulinginterval')),
                ('scheduling_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scheduling_ht', to='description.timeperiod')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='host_templates',
            field=models.ManyToManyField(blank=True, null=True, to='description.HostTemplate'),
        ),
        migrations.AddField(
            model_name='metric',
            name='metric_template',
            field=models.ManyToManyField(blank=True, null=True, to='description.MetricTemplate'),
        ),
    ]
