# Generated by Django 3.2.4 on 2021-07-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0013_auto_20210629_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='metric_template',
            new_name='metric_templates',
        ),
        migrations.RemoveField(
            model_name='metrictemplate',
            name='metric_template',
        ),
        migrations.AddField(
            model_name='metrictemplate',
            name='metric_templates',
            field=models.ManyToManyField(blank=True, related_name='_description_metrictemplate_metric_templates_+', to='description.MetricTemplate'),
        ),
    ]
