# Generated by Django 3.2.4 on 2021-07-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0018_alter_host_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
