# Generated by Django 3.2.4 on 2021-07-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0022_remove_metrictemplate_linked_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='globalvariable',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='hosttemplate',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='metrictemplate',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
