# Generated by Django 3.2.6 on 2021-08-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_address', models.CharField(default='', max_length=256)),
                ('web_port', models.PositiveIntegerField(default=4443)),
            ],
        ),
    ]
