# Generated by Django 3.2.6 on 2021-08-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_configurationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationmodel',
            name='secret',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='configurationmodel',
            name='web_secret',
            field=models.CharField(default='', max_length=255),
        ),
    ]
