# Generated by Django 3.2.6 on 2021-08-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210823_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationmodel',
            name='proxy_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
