# Generated by Django 3.2.4 on 2021-06-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0004_variable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.PositiveIntegerField(default=350)),
            ],
        ),
    ]
