# Generated by Django 3.2.4 on 2021-06-19 21:28

from django.db import migrations, models
import django.db.models.deletion

from description.models import Day, DayTimePeriod, Period, TimePeriod


def create_days(*args):
    days = [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday"
    ]
    for day in days:
        d, created = Day.objects.get_or_create(name=day)
        if created:
            d.save()


def create_default_time_periods(*args):
    days = [x for x in Day.objects.all()]
    period, created = Period.objects.get_or_create(start_time="0000", stop_time="2400")
    dtps = []
    if created:
        period.save()
    for day in days:
        dtp = [x for x in DayTimePeriod.objects.filter(day=day)]
        for item in dtp:
            if period in item.periods and len(item.periods) == 1:
                dtps.append(item)
                break
        else:
            dtp = []
        if len(dtp) == 0:
            dtp = DayTimePeriod.objects.create(day=day)
            dtp.periods.add(period)
            dtp.save()
            dtps.append(dtp)
    time_period, created = TimePeriod.objects.get_or_create(name="24x7")
    if created:
        time_period.time_periods.add(*dtps)
        time_period.save()


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0007_metric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayTimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='description.day')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(default='', max_length=4)),
                ('stop_time', models.CharField(default='', max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='metric',
            name='scheduling_interval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='description.schedulinginterval'),
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('time_periods', models.ManyToManyField(to='description.DayTimePeriod')),
            ],
        ),
        migrations.AddField(
            model_name='daytimeperiod',
            name='periods',
            field=models.ManyToManyField(to='description.Period'),
        ),
        migrations.AddField(
            model_name='metric',
            name='notification_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification', to='description.timeperiod'),
        ),
        migrations.AddField(
            model_name='metric',
            name='scheduling_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scheduling', to='description.timeperiod'),
        ),
        migrations.RunPython(
            create_days
        ),
        migrations.RunPython(
            create_default_time_periods
        )
    ]
