# Generated by Django 3.2.4 on 2021-06-29 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0010_generickvp_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variable',
        ),
        migrations.AddField(
            model_name='host',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='disabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='disabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_time',
            field=models.CharField(default='', max_length=4, validators=[django.core.validators.RegexValidator('(([01][0-9]|2[0-3])[0-5][0-9]|2400)')]),
        ),
        migrations.AlterField(
            model_name='period',
            name='stop_time',
            field=models.CharField(default='', max_length=4, validators=[django.core.validators.RegexValidator('(([01][0-9]|2[0-3])[0-5][0-9]|2400)')]),
        ),
    ]
