# Generated by Django 3.2.4 on 2021-06-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0012_auto_20210629_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_templates',
            field=models.ManyToManyField(blank=True, to='description.HostTemplate'),
        ),
        migrations.AlterField(
            model_name='hosttemplate',
            name='host_templates',
            field=models.ManyToManyField(blank=True, related_name='_description_hosttemplate_host_templates_+', to='description.HostTemplate'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='metric_template',
            field=models.ManyToManyField(blank=True, to='description.MetricTemplate'),
        ),
        migrations.AlterField(
            model_name='metrictemplate',
            name='metric_template',
            field=models.ManyToManyField(blank=True, related_name='_description_metrictemplate_metric_template_+', to='description.MetricTemplate'),
        ),
    ]
