# Generated by Django 3.2.4 on 2021-07-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0020_alter_metrictemplate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='linked_host_notification_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact_host_nt', to='description.timeperiod'),
        ),
        migrations.AddField(
            model_name='contact',
            name='linked_metric_notification_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact_metric_nt', to='description.timeperiod'),
        ),
    ]
