# Generated by Django 3.2.4 on 2021-07-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0021_auto_20210721_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrictemplate',
            name='linked_host',
        ),
    ]
