# Generated by Django 3.2.6 on 2021-08-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0023_auto_20210731_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosttemplate',
            name='host_templates',
            field=models.ManyToManyField(blank=True, to='description.HostTemplate'),
        ),
        migrations.AlterField(
            model_name='metrictemplate',
            name='metric_templates',
            field=models.ManyToManyField(blank=True, to='description.MetricTemplate'),
        ),
    ]
