# Generated by Django 3.2.6 on 2021-08-07 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0024_auto_20210806_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('address', models.CharField(default='', max_length=255)),
                ('port', models.PositiveIntegerField(default=8443)),
                ('disabled', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, default='', max_length=1024, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='linked_proxy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='description.proxy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hosttemplate',
            name='linked_proxy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='description.proxy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='linked_proxy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='description.proxy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metrictemplate',
            name='linked_proxy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='description.proxy'),
            preserve_default=False,
        ),
    ]
