# Generated by Django 3.2.6 on 2021-08-08 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0025_auto_20210807_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosttemplate',
            name='linked_proxy',
        ),
        migrations.RemoveField(
            model_name='metrictemplate',
            name='linked_proxy',
        ),
    ]
