# Generated by Django 3.2.6 on 2021-08-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0027_auto_20210816_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='port',
            field=models.PositiveIntegerField(default=8443),
        ),
        migrations.AddField(
            model_name='proxy',
            name='web_port',
            field=models.PositiveIntegerField(default=4443),
        ),
    ]
