# Generated by Django 3.2.6 on 2021-08-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0028_auto_20210817_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='secret',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='proxy',
            name='web_secret',
            field=models.CharField(default='', max_length=255),
        ),
    ]
