# Generated by Django 4.0.1 on 2022-02-10 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.CharField(default='', max_length=8192)),
                ('meta_process_end_time', models.DateTimeField()),
                ('meta_process_execution_time', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CheckState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('linked_check_results', models.ManyToManyField(blank=True, to='proxy.CheckResult')),
            ],
        ),
        migrations.AddField(
            model_name='checkresult',
            name='data_sets',
            field=models.ManyToManyField(to='proxy.DataSet'),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proxy.checkstate'),
        ),
    ]
