# Generated by Django 3.2.6 on 2021-08-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdout', models.CharField(default='', max_length=8192)),
                ('return_code', models.IntegerField(default=-1)),
                ('linked_object', models.IntegerField(default=0)),
                ('linked_object_type', models.IntegerField(default=0)),
                ('meta_process_time', models.DateTimeField()),
                ('meta_process_execution_time', models.FloatField()),
                ('linked_data', models.ManyToManyField(blank=True, to='proxy.DataModel')),
            ],
        ),
    ]
