# Generated by Django 3.2.6 on 2021-08-24 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='checkresult',
            old_name='meta_process_time',
            new_name='meta_process_end_time',
        ),
        migrations.RenameField(
            model_name='checkresult',
            old_name='stdout',
            new_name='output',
        ),
        migrations.RemoveField(
            model_name='checkresult',
            name='linked_data',
        ),
        migrations.RemoveField(
            model_name='checkresult',
            name='linked_object',
        ),
        migrations.RemoveField(
            model_name='checkresult',
            name='linked_object_type',
        ),
        migrations.RemoveField(
            model_name='checkresult',
            name='return_code',
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='meta_process_execution_time',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='DataModel',
        ),
        migrations.AddField(
            model_name='checkresult',
            name='data_sets',
            field=models.ManyToManyField(to='proxy.DataSet'),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proxy.checkstate'),
        ),
    ]
