# Generated by Django 3.2.6 on 2021-08-28 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('proxy', '0003_auto_20210827_1923_squashed_0004_alter_checkresult_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkresult',
            name='context',
        ),
        migrations.RemoveField(
            model_name='checkresult',
            name='object_id',
        ),
        migrations.CreateModel(
            name='ScheduledObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('linked_check_results', models.ManyToManyField(blank=True, to='proxy.CheckResult')),
            ],
        ),
    ]
