# Generated by Django 3.2.4 on 2021-06-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accountmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecretModel',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='username',
        ),
    ]
