# Generated by Django 3.2.4 on 2021-06-30 14:58

from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# api.migrations.0004_auto_20210630_1427_squashed_0005_aclgroupmodel_name


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210630_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('allow', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ACLGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_acls', models.ManyToManyField(to='api.ACLModel')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='linked_acl_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.aclgroupmodel'),
        ),
        migrations.AlterField(
            model_name='aclgroupmodel',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='aclgroupmodel',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
