# Generated by Django 3.2.4 on 2021-06-30 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210630_1427_squashed_0005_aclgroupmodel_name_squashed_0005_alter_aclgroupmodel_name_squashed_0006_alter_aclgroupmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='linked_acl_group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='api.aclgroupmodel'),
        ),
    ]
