# Generated by Django 3.2.4 on 2021-06-30 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('description', '0013_auto_20210629_2130'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255)),
                ('firstname', models.CharField(default='', max_length=255)),
                ('surname', models.CharField(default='', max_length=255)),
                ('mail', models.EmailField(blank=True, default='', max_length=255, null=True)),
                ('internal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notification_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_acc', to='description.timeperiod')),
            ],
        ),
    ]
