# Generated by Django 4.0.1 on 2022-01-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accountmodel_notification_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='linked_api_tokens',
        ),
        migrations.DeleteModel(
            name='APIToken',
        ),
    ]
