# Generated by Django 4.0.2 on 2022-02-20 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='linked_metric_notification_period',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='linked_metric_notifications',
        ),
        migrations.AddField(
            model_name='contact',
            name='linked_observable_notification_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact_observable_nt', to='api.timeperiod'),
        ),
        migrations.AddField(
            model_name='contact',
            name='linked_observable_notifications',
            field=models.ManyToManyField(blank=True, related_name='contact_observable_check', to='api.Check'),
        ),
    ]
